version: 2.1

jobs:
  analyze:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Get GitHub PullRequest Number
          command: >-
            if [[ -z "$CIRCLE_PR_NUMBER" ]]; then
                if [[ -z "$CI_PULL_REQUEST" ]]; then
                    URL="https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH"
                    RESULT="`curl -X GET -u $GITHUB_ACCESS_TOKEN:x-oauth-basic $URL | jq ".[0].url"`"
                    [[ "$RESULT" == 'null' ]] && CI_PULL_REQUEST='' || CI_PULL_REQUEST="${RESULT//\"}"
                fi
                CIRCLE_PR_NUMBER="$(basename "$CI_PULL_REQUEST")"
            fi

            echo 'export CIRCLE_PR_NUMBER=$CIRCLE_PR_NUMBER' >> $BASH_ENV
      - run:
          name: SonarQube - PullRequest Scan
          command: >-
            sonar-scanner
            -X
            -Dsonar.login=$SONAR_TOKEN
            -Dsonar.host.url=$SONAR_HOST_URL
            -Dsonar.pullrequest.key=${CIRCLE_PULL_REQUEST##*/}
            -Dsonar.pullrequest.branch=$CIRCLE_BRANCH
            -Dsonar.pullrequest.base=main
            -Dsonar.qualitygate.wait=true
            -Dsonar.qualitygate.timeout=300
            -Dsonar.projectVersion=$CIRCLE_SHA1
  analyze_branch:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: SonarQube - Push Scan
          command: >-
            sonar-scanner
            -X
            -Dsonar.login=$SONAR_TOKEN
            -Dsonar.host.url=$SONAR_HOST_URL
            -Dsonar.branch.name=main

workflows:
  version: 2
  app:
    jobs:
      - analyze:
          filters:
            branches:
              ignore:
                - develop
                - master
                - main
      - analyze_branch:
          filters:
            branches:
              only:
                - main
